[package]
name = "gift-file-type"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "gft"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.3", features = ["derive"] }
csv = "1.2.2"
html-escape = "0.2.13"
regex = "1.9.5"
